In [2]:
## SPEI data from google earth engine
import os
import ee
import geemap
import pandas as pd
import datetime
from datetime import date
import numpy as np

In [4]:
gridmet = ee.ImageCollection('GRIDMET/DROUGHT')

In [3]:
full_df = pd.read_csv("samples_to_get.csv")[["dnaSampleID", "collectDate", "long", "lat"]]

In [4]:
type(full_df)

pandas.core.frame.DataFrame

In [8]:
def get_spei(latitude_in, longitude_in, date_in, offset = 5, scale = 4000):
    end_date = datetime.date.fromisoformat(date_in)
    begin_date = end_date - datetime.timedelta(days=offset)   
    try:
        coord = ee.Geometry.Point(longitude_in, latitude_in)
        lst = gridmet.select('spi30d', 'spi90d', 'spi180d', 'spi270d',
         'spi1y', 'spi2y', 'spi5y', 'spei30d', 'spei90d', 'spei180d', 'spei270d',
                             'spei1y', 'spei2y', 'spei5y').filterDate( begin_date.isoformat(), end_date.isoformat())
        sample_spi_30d = lst.mean().sample(coord, scale).first().get('spi30d').getInfo()
        sample_spi_90d = lst.mean().sample(coord, scale).first().get('spi90d').getInfo()
        sample_spi_180d = lst.mean().sample(coord, scale).first().get('spi180d').getInfo()
        sample_spi_270d = lst.mean().sample(coord, scale).first().get('spi270d').getInfo()
        sample_spi_1 = lst.mean().sample(coord, scale).first().get('spi1y').getInfo()
        sample_spi_2 = lst.mean().sample(coord, scale).first().get('spi2y').getInfo()
        sample_spi_5 = lst.mean().sample(coord, scale).first().get('spi5y').getInfo()
        sample_spei_30d = lst.mean().sample(coord, scale).first().get('spei30d').getInfo()
        sample_spei_90d = lst.mean().sample(coord, scale).first().get('spei90d').getInfo()
        sample_spei_180d = lst.mean().sample(coord, scale).first().get('spei180d').getInfo()
        sample_spei_270d = lst.mean().sample(coord, scale).first().get('spei270d').getInfo()
        sample_spei_1 = lst.mean().sample(coord, scale).first().get('spei1y').getInfo()
        sample_spei_2 = lst.mean().sample(coord, scale).first().get('spei2y').getInfo()
        sample_spei_5 = lst.mean().sample(coord, scale).first().get('spei5y').getInfo()
        return(sample_spi_30d, sample_spi_90d, sample_spi_180d, 
               sample_spi_270d, sample_spi_1, sample_spi_2, sample_spi_5,
               sample_spei_30d, sample_spei_90d, sample_spei_180d, 
               sample_spei_270d, sample_spei_1, sample_spei_2, sample_spei_5)
    except:
        print("NA")

In [9]:
full_df[['spi30d', 'spi90d', 'spi180d', 'spi270d',
         'spi1y', 'spi2y', 'spi5y',
         'spei30d', 'spei90d', 'spei180d', 'spei270d',
                             'spei1y', 'spei2y', 'spei5y', 'test']] = np.nan

In [14]:
i = 0
for index, row in full_df.iterrows():
    latitude = row["lat"]
    longitude = row["long"]
    sampleDate = row["collectDate"]
    print(sampleDate)
    full_df.loc[i, ['spi30d', 'spi90d', 'spi180d', 'spi270d',
         'spi1y', 'spi2y', 'spi5y','spei30d', 'spei90d', 'spei180d', 'spei270d',
                    'spei1y', 'spei2y', 'spei5y']] = get_spei(latitude_in=latitude, 
                                                              longitude_in=longitude, 
                                                              date_in=sampleDate
                                                             )
    full_df.loc[i, 'test'] = longitude
    i += 1

2016-08-09

AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'

In [46]:
full_df

,dnaSampleID,collectDate,long,lat,spi30d,spi90d,spi180d,spi270d,spi1y,spi2y,spi5y,spei30d,spei90d,spei180d,spei270d,spei1y,spei2y,spei5y,test
0,OAES_045-M-20160809-COMP-DNA1,2016-08-09,-99.057569,35.410788,-0.24,-1.01,-0.90,-0.54,-1.45,-0.03,-1.13,-0.46,-0.62,-0.80,-0.54,-0.71,-0.10,-1.13,-99.057569
1,CPER_006-M-20180702-COMP-DNA1,2018-07-02,-104.748078,40.814769,-0.62,0.32,0.63,0.24,0.39,0.10,2.09,-0.71,-0.24,-0.17,-0.62,-0.24,-0.54,1.13,-104.748078
2,DEJU_047-O-20180621-COMP-DNA1,2018-06-21,-145.739248,63.882240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-145.739248
3,GRSM_060-O-20160719-COMP-DNA1,2016-07-19,-83.503985,35.686010,0.10,-0.62,-1.01,-0.46,-0.62,-0.32,2.09,0.10,-0.62,-1.13,-0.62,-0.54,-0.32,0.32,-83.503985
4,CPER_002-M-20160719-COMP-DNA1,2016-07-19,-104.729248,40.810934,-0.24,-0.10,0.32,0.71,0.47,1.28,0.71,-0.17,0.17,0.10,0.24,-0.03,1.01,-0.54,-104.729248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,OAES_043-M-20170627-COMP-DNA1,2017-06-27,-99.058568,35.405108,-1.01,0.80,0.47,-0.24,0.54,-0.39,-1.01,-0.71,0.63,0.10,-0.24,0.03,-0.54,-1.01,-99.058568
382,STEI_003-O-20160720-COMP-DNA1,2016-07-20,-90.072607,45.824940,0.24,0.71,0.63,2.09,1.01,1.01,1.13,0.17,0.71,0.47,2.09,0.63,1.13,-0.17,-90.072607
383,SOAP_004-M-20180530-COMP-DNA1,2018-05-30,-119.269483,37.037426,-2.09,1.01,-0.10,-0.24,-0.24,0.90,-0.46,-0.62,0.80,-0.17,-0.24,-0.32,0.80,-0.46,-119.269483
384,ORNL_043-M-20170621-COMP-DNA1,2017-06-21,-84.287233,35.963926,0.03,0.90,0.63,0.17,-0.46,0.10,2.09,-0.03,0.54,0.17,-0.39,-0.90,-0.39,-0.90,-84.287233
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
full_df.to_csv("../../data/input/derived/spei.csv")